[package]
name = "dmgwiz"
version = "0.1.0"
authors = ["Felix Seele <fseele@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.0"
clap = "2.33.0"
bincode = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
ring = "0.16.9"
openssl = { version = "0.10", features = ["vendored"] }
plist = "0.5"